# Diabetes Prediciton Using Logistic Regression

## Goal:
### To build out a Logistic Regression model using SGPGI Hospital data for diabetes predicition.

## Importing Required Library

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE
from sklearn.linear_model import LogisticRegression
import pickle

## Loading Dataset

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
df = pd.read_excel('/content/drive/MyDrive/patients_data.xlsx')
df.head()

,Treatment,Age,Gender,Obesity,Diabetes,Hypertension,Blood_pressure,Smoker,Cholestrol,Cholestrol2,Angina,FBS,Hemglobin,CRP1,CRP2,CRP3,AgeGroups,haemoglobingroups
0,2,52,1,2,2,2,1,2,2,3,2,111,11,23,19,17,2,1
1,2,51,2,2,2,2,1,2,2,3,2,115,12,18,14,12,2,1
2,2,47,2,2,1,2,2,2,2,3,2,100,11,25,21,19,1,1
3,2,56,2,2,2,2,2,1,2,3,1,117,14,18,14,12,2,2
4,2,50,1,2,2,2,1,2,2,3,2,111,11,20,18,14,1,1

## Data Preprocessing

### Removing Unnecessary Features

In [4]:
df.drop(columns=['Treatment', 'Cholestrol2','CRP1', 'CRP2', 'CRP3', 'AgeGroups', 'haemoglobingroups' ])

,Age,Gender,Obesity,Diabetes,Hypertension,Blood_pressure,Smoker,Cholestrol,Angina,FBS,Hemglobin
0,52,1,2,2,2,1,2,2,2,111,11
1,51,2,2,2,2,1,2,2,2,115,12
2,47,2,2,1,2,2,2,2,2,100,11
3,56,2,2,2,2,2,1,2,1,117,14
4,50,1,2,2,2,1,2,2,2,111,11
...,...,...,...,...,...,...,...,...,...,...,...
795,68,1,1,2,2,1,1,1,1,121,12
796,77,1,1,2,2,1,2,1,2,119,10
797,70,1,1,2,2,1,2,1,1,117,8
798,52,2,2,2,2,1,2,1,1,118,9
799,68,2,1,2,2,1,1,1,1,114,5

### Data Encoding

In [5]:
df_model=df.copy()
binary = {1:1, 2:0}
colms=['Gender',	'Obesity', 'Diabetes',	'Hypertension','Blood_pressure',	'Smoker',	'Cholestrol', 'Angina',]

### Data Splitting

In [6]:
X=df_model.drop('Diabetes', axis=1)
y=df_model['Diabetes']
X_train, X_test, y_train, y_test = train_test_split(X,y, stratify=y, random_state=42)

### Class Balancing

In [7]:
sm=SMOTE(random_state=42)
X_train_bal, y_train_bal=sm.fit_resample(X_train,y_train)

## Logistic Regression Model

#### Model Building

In [11]:
lr_model=LogisticRegression(max_iter=1000, class_weight="balanced")
lr_model.fit(X_train_bal, y_train_bal)

LogisticRegression(class_weight='balanced', max_iter=1000)

### Pickle Model

In [12]:
pickle.dump(
    lr_model, open('logisticReg_model.pickle', 'wb')
)